set(_CATKIN_CURRENT_PACKAGE "log_tutorial")
set(log_tutorial_VERSION "0.0.0")
set(log_tutorial_MAINTAINER "xkl <xkl@todo.todo>")
set(log_tutorial_PACKAGE_FORMAT "2")
set(log_tutorial_BUILD_DEPENDS "roscpp" "std_msgs")
set(log_tutorial_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(log_tutorial_BUILDTOOL_DEPENDS "catkin")
set(log_tutorial_BUILDTOOL_EXPORT_DEPENDS )
set(log_tutorial_EXEC_DEPENDS "roscpp" "std_msgs")
set(log_tutorial_RUN_DEPENDS "roscpp" "std_msgs")
set(log_tutorial_TEST_DEPENDS )
set(log_tutorial_DOC_DEPENDS )
set(log_tutorial_URL_WEBSITE "")
set(log_tutorial_URL_BUGTRACKER "")
set(log_tutorial_URL_REPOSITORY "")
set(log_tutorial_DEPRECATED "")