set(_CATKIN_CURRENT_PACKAGE "monitor_all_bt")
set(monitor_all_bt_VERSION "0.0.0")
set(monitor_all_bt_MAINTAINER "xkl <xkl@todo.todo>")
set(monitor_all_bt_PACKAGE_FORMAT "2")
set(monitor_all_bt_BUILD_DEPENDS "rospy" "std_msgs")
set(monitor_all_bt_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(monitor_all_bt_BUILDTOOL_DEPENDS "catkin")
set(monitor_all_bt_BUILDTOOL_EXPORT_DEPENDS )
set(monitor_all_bt_EXEC_DEPENDS "rospy" "std_msgs")
set(monitor_all_bt_RUN_DEPENDS "rospy" "std_msgs")
set(monitor_all_bt_TEST_DEPENDS )
set(monitor_all_bt_DOC_DEPENDS )
set(monitor_all_bt_URL_WEBSITE "")
set(monitor_all_bt_URL_BUGTRACKER "")
set(monitor_all_bt_URL_REPOSITORY "")
set(monitor_all_bt_DEPRECATED "")